//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPC_DesktopV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class cMCSFG
    {
        public string MCSFGID { get; set; }
        public string MCSID { get; set; }
        public string No { get; set; }
        public string CheckItem { get; set; }
        public string NominalValue { get; set; }
        public string CTQMin { get; set; }
        public string CTQMax { get; set; }
        public string Min { get; set; }
        public string Max { get; set; }
        public string Unit { get; set; }
        public string Method { get; set; }
        public string CTQ { get; set; }
        public string DataType { get; set; }
        public string InspectionStatus { get; set; }
        public string Process { get; set; }
        public string Remark { get; set; }
        public string SAPCode { get; set; }
        public string PartCode { get; set; }
        public string InspectionData { get; set; }
        public string Calculation { get; set; }
        public int MPCNo { get; set; }
        public string MPCCriteria { get; set; }
        public string SidePosition { get; set; }
        public string ProductCode { get; set; }
        public string CodeName { get; set; }
        public string Image { get; set; }
        public string RegisterID { get; set; }
        public string RegisterPG { get; set; }
        public System.DateTime RegisterDate { get; set; }
        public string UpdateID { get; set; }
        public string UpdatePG { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
    }
}
