//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPC_DesktopV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class iInspectionItem
    {
        public long ID { get; set; }
        public string MCSID { get; set; }
        public string MCSChildID { get; set; }
        public string CheckItem { get; set; }
        public string Stage { get; set; }
        public string SAPCode { get; set; }
        public bool IsSAC { get; set; }
        public string SACLSL { get; set; }
        public string SACUSL { get; set; }
        public decimal SACQty { get; set; }
        public decimal SACQtyUsed { get; set; }
        public System.DateTime SACStart { get; set; }
        public System.DateTime SACEnd { get; set; }
        public string SACNumber { get; set; }
        public string CTQ { get; set; }
        public int Qty { get; set; }
        public string LotNo { get; set; }
        public string Supplier { get; set; }
        public int SamplingSize { get; set; }
        public string OverallJudgement { get; set; }
        public string InspectorRemark { get; set; }
        public bool IsPartial { get; set; }
        public bool IsFinished { get; set; }
        public bool IsDeleted { get; set; }
        public string RegisterID { get; set; }
        public string RegisterPG { get; set; }
        public System.DateTime RegisterDate { get; set; }
        public string UpdateID { get; set; }
        public string UpdatePG { get; set; }
        public System.DateTime UpdateDate { get; set; }
    }
}
