//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPC_DesktopV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class iInspectionDetail
    {
        public long ID { get; set; }
        public Nullable<long> InspectionItemId { get; set; }
        public string CheckItemNo { get; set; }
        public int Sequence { get; set; }
        public decimal Data { get; set; }
        public string Judgement { get; set; }
        public bool IsPartial { get; set; }
        public bool IsFinished { get; set; }
        public bool IsDeleted { get; set; }
        public string RegisterID { get; set; }
        public string RegisterPG { get; set; }
        public System.DateTime RegisterDate { get; set; }
        public string UpdateID { get; set; }
        public string UpdatePG { get; set; }
        public System.DateTime UpdateDate { get; set; }
    }
}
