//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPC_DesktopV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class mImageSAC
    {
        public long ID { get; set; }
        public string Image_URL { get; set; }
        public string FileName { get; set; }
        public string SACRef { get; set; }
    }
}
