//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPC_DesktopV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class mInstrument
    {
        public long InstrumentID { get; set; }
        public string InstrumentCode { get; set; }
        public string InstrumentName { get; set; }
        public long TerminalID { get; set; }
        public string USBPort { get; set; }
        public bool IsDeleted { get; set; }
        public string RegisterID { get; set; }
        public string RegisterPG { get; set; }
        public System.DateTime RegisterDate { get; set; }
        public string UpdateID { get; set; }
        public string UpdatePG { get; set; }
        public System.DateTime UpdateDate { get; set; }
    }
}
