//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPC_DesktopV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class mUser
    {
        public string UserID { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public string UserAccess { get; set; }
        public string Department { get; set; }
        public bool MGTModule { get; set; }
        public bool MCSModule { get; set; }
        public bool INSModule { get; set; }
        public bool RPTModule { get; set; }
        public Nullable<bool> Incomplete_Inspection { get; set; }
        public Nullable<bool> Can_Approved { get; set; }
        public Nullable<bool> Can_Request { get; set; }
        public int LoginAttempts { get; set; }
        public bool IsLocked { get; set; }
        public bool IsDeleted { get; set; }
        public string RegisterID { get; set; }
        public string RegisterPG { get; set; }
        public System.DateTime RegisterDate { get; set; }
        public string UpdateID { get; set; }
        public string UpdatePG { get; set; }
        public System.DateTime UpdateDate { get; set; }
    }
}
