//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPC_DesktopV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class rMonthly
    {
        public int id { get; set; }
        public string Type { get; set; }
        public string ProductCode { get; set; }
        public string PartNo { get; set; }
        public string PartName { get; set; }
        public string Process { get; set; }
        public string CheckItem { get; set; }
        public string Stage { get; set; }
        public string Supplier { get; set; }
        public string UT { get; set; }
        public string LT { get; set; }
        public decimal Cpk { get; set; }
        public int Month { get; set; }
        public int Year { get; set; }
    }
}
