//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPC_DesktopV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCoefficient
    {
        public int id { get; set; }
        public int N { get; set; }
        public Nullable<decimal> A2 { get; set; }
        public Nullable<decimal> D3 { get; set; }
        public Nullable<decimal> D4 { get; set; }
        public Nullable<decimal> B3 { get; set; }
        public Nullable<decimal> B4 { get; set; }
        public Nullable<decimal> C4 { get; set; }
    }
}
