//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPC_DesktopV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSigmaTable
    {
        public int ID { get; set; }
        public decimal ncpu { get; set; }
        public long ncpmo { get; set; }
        public decimal sigma { get; set; }
    }
}
