//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPC_DesktopV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class xNCMailTextLog
    {
        public int ID { get; set; }
        public string TextEmail { get; set; }
        public string ResultMsg { get; set; }
        public string SqlQuery { get; set; }
        public string SqlMessage { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
