//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPC_DesktopV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class xNCMailLog
    {
        public int ID { get; set; }
        public string MCSID { get; set; }
        public string MCSChildID { get; set; }
        public string InspectionItemID { get; set; }
        public string SAPCode { get; set; }
        public string LotNo { get; set; }
        public int Qty { get; set; }
        public string OverAllJudgement { get; set; }
        public bool IsEmailSent { get; set; }
        public System.DateTime RecordDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
    }
}
